# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# PHP version used in first build configuration.
php:
    - 5.5
# WordPress version used in first build configuration.
env:
    - WP_VERSION=master WP_MULTISITE=0
#     - WP_VERSION=master WP_MULTISITE=0
#    - WP_VERSION=3.8.1 WP_MULTISITE=0
#    - WP_VERSION=3.7.1 WP_MULTISITE=0
#    - WP_VERSION=3.6.1 WP_MULTISITE=0
#    - WP_VERSION=3.5.2 WP_MULTISITE=0
#    - WP_VERSION=master WP_MULTISITE=1
#    - WP_VERSION=3.8.1 WP_MULTISITE=1
#    - WP_VERSION=3.7.1 WP_MULTISITE=1
#    - WP_VERSION=3.6.1 WP_MULTISITE=1
#    - WP_VERSION=3.5.2 WP_MULTISITE=1

# Next we define our matrix of additional build configurations to test against.
# The versions listed above will automatically create our first configuration,
# so it doesn't need to be re-defined below.

# WP_VERSION specifies the tag to use. The way these tests are configured to run
# requires at least WordPress 3.8. Specify "master" to test against SVN trunk.

# Note that Travis CI supports listing these above to automatically build a
# matrix of configurations, but we're being nice here by manually building a
# total of four configurations even though we're testing 4 versions of PHP
# along with 2 versions of WordPress (which would build 8 configs otherwise).
# This takes half as long to run while still providing adequate coverage.

# matrix:
#  include:
#    - php: "5.3"
#      env: WP_VERSION=master WP_MULTISITE=1
#    - php: "5.4"
#      env: WP_VERSION=3.8 WP_MULTISITE=0
#    - php: "5.2"
#      env: WP_VERSION=3.8 WP_MULTISITE=0

before_script:
    - set -x
    # set up WP install
#    - WP_CORE_DIR=/tmp/wordpress/
#    - WP_DEVELOP_DIR=/tmp/wordpress/
#    - wget -nv -O /tmp/wordpress.tar.gz https://github.com/WordPress/WordPress/tarball/$WP_VERSION
#    - mkdir -p $WP_CORE_DIR
#    - tar --strip-components=1 -zxmf /tmp/wordpress.tar.gz -C $WP_CORE_DIR
#    - plugin_slug=$(basename $(pwd))
#    - plugin_dir=$WP_CORE_DIR/wp-content/plugins/$plugin_slug
#   - cd ..
#   - mv $plugin_slug $plugin_dir
    # set up testing suite
#    - export WP_TESTS_DIR=/tmp/wordpress-tests/
#    - svn co --ignore-externals http://unit-tests.svn.wordpress.org/trunk/ $WP_TESTS_DIR
#   - cd $WP_TESTS_DIR
#   - cp wp-tests-config-sample.php wp-tests-config.php
#   - sed -i "s:dirname( __FILE__ ) . '/wordpress/':'$WP_CORE_DIR':" wp-tests-config.php
#   - sed -i "s/yourdbnamehere/wordpress_test/" wp-tests-config.php
#   - sed -i "s/yourusernamehere/root/" wp-tests-config.php
#   - sed -i "s/yourpasswordhere//" wp-tests-config.php
    # set up database
#   - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
    # prepare for running the tests
#   - cd $plugin_dir
    #new alt build with grunt and wp develop repo
#    - WP_DEVELOP_DIR=tmp/wordpress
#    - BBP_DEVELOP_DIR=ntwb/bbPress
#    - mkdir -p $WP_DEVELOP_DIR
    # setup db
#    - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
    # grab wp branch
#    - git clone --branch=$WP_VERSION git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
#    - cd $WP_DEVELOP_DIR
    # setub wp-configs
#    - cp wp-tests-config-sample.php wp-tests-config.php
#    - sed -i "s:dirname( __FILE__ ) . '/wordpress/':'$WP_DEVELOP_DIR':" wp-tests-config.php
#    - sed -i "s/yourdbnamehere/wordpress_test/" wp-tests-config.php
#    - sed -i "s/yourusernamehere/root/" wp-tests-config.php
#    - sed -i "s/yourpasswordhere//" wp-tests-config.php
    # 'build' wp
#    - npm install -g grunt-cli
#    - npm install
#    - grunt build
#    - cd ..
#    - cd ..
    # bbPress' turn
#    - plugin_dir=$WP_DEVELOP_DIR/build/wp-content/plugins/$BBP_DEVELOP_DIR
#    - cd ..
#    - mv $BBP_DEVELOP_DIR $plugin_dir
    # prepare for running bbPress' tests
#    - cd $plugin_dir
    # 'build' bbPress
#    - npm install -g grunt-cli
#    - npm install
#    - grunt build
    # Lets try @tiera's way via https://github.com/tierra/wordpress-plugin-tests
    - export PLUGIN_SLUG=$(basename $(pwd))
    - git clone git://develop.git.wordpress.org/ /tmp/wordpress
#    - git clone . "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
#    - mv $plugin_slug /tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG
    - mv $TRAVIS_REPO_SLUG /tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG
    - cd /tmp/wordpress
    - git checkout $WP_VERSION
    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    - cp wp-tests-config-sample.php wp-tests-config.php
    - sed -i "s:dirname( __FILE__ ) . '/wordpress/':'$WP_DEVELOP_DIR':" wp-tests-config.php
    - sed -i "s/yourdbnamehere/wordpress_test/" wp-tests-config.php
    - sed -i "s/yourusernamehere/root/" wp-tests-config.php
    - sed -i "s/yourpasswordhere//" wp-tests-config.php

script: phpunit
# script: grunt travis

notifications:
    email: false

#    irc:
#        channels:
#            - "irc.freenode.net#bbpress-dev"
#        template:
#            - "Build %{build_number} (%{branch} - %{commit}): %{message} %{build_url}"