# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# PHP version used in first build configuration.
php:
    - 5.5
# WordPress version used in first build configuration.
env:
    - WP_VERSION=master WP_MULTISITE=0
#     - WP_VERSION=master WP_MULTISITE=0
#    - WP_VERSION=3.8.1 WP_MULTISITE=0
#    - WP_VERSION=3.7.1 WP_MULTISITE=0
#    - WP_VERSION=3.6.1 WP_MULTISITE=0
#    - WP_VERSION=3.5.2 WP_MULTISITE=0
#    - WP_VERSION=master WP_MULTISITE=1
#    - WP_VERSION=3.8.1 WP_MULTISITE=1
#    - WP_VERSION=3.7.1 WP_MULTISITE=1
#    - WP_VERSION=3.6.1 WP_MULTISITE=1
#    - WP_VERSION=3.5.2 WP_MULTISITE=1

# Next we define our matrix of additional build configurations to test against.
# The versions listed above will automatically create our first configuration,
# so it doesn't need to be re-defined below.

# WP_VERSION specifies the tag to use. The way these tests are configured to run
# requires at least WordPress 3.8. Specify "master" to test against SVN trunk.

# Note that Travis CI supports listing these above to automatically build a
# matrix of configurations, but we're being nice here by manually building a
# total of four configurations even though we're testing 4 versions of PHP
# along with 2 versions of WordPress (which would build 8 configs otherwise).
# This takes half as long to run while still providing adequate coverage.

matrix:
    include:
    - php: "5.3"
      env: WP_VERSION=master WP_MULTISITE=0
    - php: "5.3"
      env: WP_VERSION=master WP_MULTISITE=1

before_script:
    # Lets try @tiera's way via https://github.com/tierra/wordpress-plugin-tests
    - WP_DEVELOP_DIR=/tmp/wordpress
    - git clone git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
    - mv $TRAVIS_BUILD_DIR /tmp/wordpress/src/wp-content/plugins/bbpress
    - cd $WP_DEVELOP_DIR
    - git checkout $WP_VERSION
    # setub db
    - mysql -e "CREATE DATABASE wordpress_test;" -uroot
    # setub wp-configs
    - cp wp-tests-config-sample.php wp-tests-config.php
    - sed -i "s:dirname( __FILE__ ) . '/wordpress/':'$WP_DEVELOP_DIR':" wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
    - sed -i "s/yourusernamehere/root/" wp-tests-config.php
    - sed -i "s/yourpasswordhere//" wp-tests-config.php
    # prepare for running bbPress' tests
    - BBP_DEVELOP_DIR=$WP_DEVELOP_DIR/src/wp-content/plugins/bbpress
    - cd $BBP_DEVELOP_DIR
    # 'build' bbPress
    - npm install -g grunt-cli
    - npm install
    - grunt build

# script: phpunit
script: grunt travis

notifications:
    email: false

#    irc:
#        channels:
#            - "irc.freenode.net#bbpress-dev"
#        template:
#            - "Build %{build_number} (%{branch} - %{commit}): %{message} %{build_url}"