# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# PHP version used in first build configuration.
php:
    - 5.2
    - 5.3
    - 5.4
    - 5.5

# WordPress versions 3.7.x and above as 'develop' repo
env:
    - WP_VERSION=master WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=0
    - WP_VERSION=3.7.1 WP_MULTISITE=0
    - WP_VERSION=master WP_MULTISITE=1
    - WP_VERSION=3.8 WP_MULTISITE=1
    - WP_VERSION=3.7.1 WP_MULTISITE=1

before_script:
    # setup WP_DEVELOP_DIR (needed for bbPress to bootstrap WP PhpUnit tests)
    - WP_DEVELOP_DIR=/tmp/wordpress
    # clone the WordPress develop repo
    - git clone git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
    - mv $TRAVIS_BUILD_DIR /tmp/wordpress/src/wp-content/plugins/bbpress
    - cd $WP_DEVELOP_DIR
    - git checkout $WP_VERSION
    # setub db
    - mysql -e "CREATE DATABASE wordpress_test;" -uroot
    # setub wp-config
    - cp wp-tests-config-sample.php wp-tests-config.php
    - sed -i "s:dirname( __FILE__ ) . '/wordpress/':'$WP_DEVELOP_DIR':" wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
    - sed -i "s/yourusernamehere/root/" wp-tests-config.php
    - sed -i "s/yourpasswordhere//" wp-tests-config.php
    # prepare for running bbPress' tests
    - BBP_DEVELOP_DIR=$WP_DEVELOP_DIR/src/wp-content/plugins/bbpress
    - cd $BBP_DEVELOP_DIR
    # 'build' bbPress
    - npm install -g grunt-cli
    - npm install
    - grunt build

# script: phpunit
script: grunt travis

notifications:
    email: false

    irc:
        channels:
            - "irc.freenode.net#bbpress-dev"
        template:
            - "Build %{build_number} (%{branch} - %{commit}): %{message} %{build_url}"